---
- name: Install remote facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  become: true
  tasks:  

  - name: Create the remote directory
    ansible.builtin.file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"

  - name: Install the new facts
    ansible.builtin.copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
